apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: auth-service-pipeline
  description: "Auth‐service pipeline for ShiftSync"
spec:
  stages:
    - targetId: staging
    - targetId: prod