pipeline {
  agent any

  environment {
    IMAGE_NAME = "australia-southeast1-docker.pkg.dev/shiftsync-gcpCT_ID/shiftsync-repo/auth-service"
    REGISTRY_CREDENTIALS = credentials('gcp-artifact-creds')
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        script {
          sh """
            docker build -t ${IMAGE_NAME}:latest .
            echo $REGISTRY_CREDENTIALS_PSW | docker login -u _json_key --password-stdin https://australia-southeast1-docker.pkg.dev
            docker push ${IMAGE_NAME}:latest
          """
        }
      }
    }
  }
}