pipeline {
  agent any

  environment {
    IMAGE_NAME = "australia-southeast1-docker.pkg.dev/shiftsync-gcp/shiftsync-repo/auth-service"
    REGISTRY_CREDENTIALS = credentials('gcp-artifact-creds')
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        script {
          def dockerLogin = 'echo %REGISTRY_CREDENTIALS_PSW% | docker login -u _json_key --password-stdin https://australia-southeast1-docker.pkg.dev'

          bat """
            cd shiftsync\\auth-service
            docker build -t ${IMAGE_NAME}:latest .
            ${dockerLogin}
            docker push ${IMAGE_NAME}:latest
          """
        }
      }
    }

    stage('Run Unit Tests') {
      steps {
        bat """
          cd shiftsync\\auth-service
          npm install
          npm test
        """
      }
    }

    stage('Code Quality Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarcloud-token', variable: 'SONAR_TOKEN')]) {
          bat '''
            cd shiftsync\\auth-service
            curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
            powershell -Command "Expand-Archive -Path sonar-scanner.zip -DestinationPath . -Force"
            .\\sonar-scanner-5.0.1.3006-windows\\bin\\sonar-scanner.bat -Dsonar.login=%SONAR_TOKEN% -Dsonar.host.url=https://sonarcloud.io -Dproject.settings=sonar-project.properties
          '''
        }
      }
    }
  }
}